services:
  web:
    image: php:apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - TZ=Asia/Phnom_Penh

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
